import fs from 'node:fs/promises'; import {execFileSync} from 'node:child_process'; import {SpreadsheetFile,Workbook} from '@oai/artifact-tool';
const py='C:\\Users\\LEGION\\.cache\\codex-runtimes\\codex-primary-runtime\\dependencies\\python\\python.exe', dir='E:\\Đề';
const code=String.raw`import json,sys
from docx import Document
d=Document(sys.argv[1]); print(json.dumps([[[c.text.strip() for c in r.cells] for r in t.rows] for t in d.tables],ensure_ascii=False))`;
const files=await fs.readdir(dir); const read=f=>JSON.parse(execFileSync(py,['-c',code,dir+'\\'+f],{encoding:'utf8',env:{...process.env,PYTHONUTF8:'1'}}));
function key(tables){const out={}; for(const table of tables) for(const row of table){for(let i=0;i+1<row.length;i+=2){const n=String(row[i]).trim(),a=String(row[i+1]).trim().toUpperCase(); if(/^\d+$/.test(n)&&a) out[Number(n)]=a;}} return out;}
const keys={}; for(let n=2;n<=11;n++){const normal=`ĐỀ ÔN LUYỆN SỐ ${String(n).padStart(2,'0')}.docx`;const f=files.includes(normal)?normal:files.find(x=>x.includes(`SỐ ${String(n).padStart(2,'0')}`));keys[String(n).padStart(2,'0')]=key(await read(f));}
const total=key(await read(files.find(x=>/T.?.NG H.P TR.C NGHI.M/i.test(x)))); const data=JSON.parse(await fs.readFile('src/data/questions.json','utf8')); const rows=[];
for(const e of data){const source=Number(e.id)<=11?keys[e.id]:Object.fromEntries(Object.entries(total).map(([n,a])=>[Number(n)-(Number(e.id)-12)*70,a]));for(const q of e.questions){const word=source[q.questionId]||'NOT FOUND';const web=String(q.correct||'');rows.push([`Đề ${e.id}`,q.questionId,word,web,word==='NOT FOUND'?'MISSING WORD KEY':word===web?'ĐÚNG':'SAI']);}}
const wb=Workbook.create(),s=wb.worksheets.add('Answer key comparison');s.getRange(`A1:E${rows.length+1}`).values=[['Đề','Câu','Đáp án Word','Đáp án Web','Kết quả'],...rows];s.getRange('A1:E1').format={fill:'#163A5F',font:{name:'Arial',bold:true,color:'#FFFFFF'},horizontalAlignment:'center'};s.getRange('A:E').format={font:{name:'Arial',size:10},verticalAlignment:'middle'};s.getRange('A:E').format.columnWidth=18;s.freezePanes.freezeRows(1);wb.recalculate();const x=await SpreadsheetFile.exportXlsx(wb);await x.save('reports/ANSWER_KEY_COMPARE_REPORT.xlsx');console.log(JSON.stringify({total:rows.length,correct:rows.filter(r=>r[4]==='ĐÚNG').length,wrong:rows.filter(r=>r[4]==='SAI').length,missing:rows.filter(r=>r[4]==='MISSING WORD KEY').length}));
